version: "3.8"
services:
  letsencrypt:
    build: .
    restart: always
    volumes:
      - ./certs:/root/.cache
    environment:
      - DOMAIN=api.dionis.cloud
    ports:
      - "80:80"
      - "443:443"
    cap_add:
      - NET_BIND_SERVICE
